### ISSUE TITLE
As developer, I want more datetime information in the API

### ISSUE THREAD

**Issue by joeribekker** [maykinmedia/objects-api#101]
We currently have `publicationDate` on ObjectTypeVersion. However, I think we should also have:

ObjectType

* [x] Add `modifiedAt` -- Reason: You can update this and it becomes unknown when this happened.
* [x] Add `createdAt` -- Reason: You can create an objecttype without a version. In that case, it's unknown when this objecttype came into existance.

ObjectTypeVersion

* [x] Add `modifiedAt` -- Reason: As long as it's in draft, you can update it without any publicationDate change.
* [x] Add `createdAt` -- Reason: Same as above, as long as not published

The `At` postfix comes from Zalando guidelines. They have some pretty nice standards and at least provide some reasoning for naming it like that: https://opensource.zalando.com/restful-api-guidelines/#235

* [x] With this in mind, we should change `publicationDate` to `publishedAt` (which will correspond to the last `modifiedAt` if published).

**Comment by annashamray** [comment]
@joeribekker Is it correct, that `publishedAt` will display the date then the version becomes `published`? 
The current `publicationDate` shows the date when the object was created. So I'll rename it to `createdAt` and add `modifiedAt` and  `publishedAt` to versions

**Comment by joeribekker** [comment]
That's correct, so yes, please change.
