### ISSUE TITLE
As a developer I want to specify which record to show in Objects API

### ISSUE THREAD

**Issue by annashamray** [maykinmedia/objects-api#108]
**Tasks**

* Let's rename `startDate` and `endDate` to `startAt` and `endAt`. Also, `registrationDate` to `registeredAt`, in line with the date fields in the Objecttypes API.

Then, add to single object and list object retrieval:

```
  record 1                                                  record 1                     record 2
  startAt                       date                         endAt                       startAt
     |----------------------------|----------------------------|----------------------------|
2020-01-01                   2020-07-01                   2020-12-31                   2021-01-01
```

* Add query param: `date=2020-07-01` (date should be between `start_at` and `end_at`)

```
  record 1                                                  record 2
registeredAt               registrationDate               registeredAt
     |----------------------------|----------------------------|
2020-01-01                   2020-07-01                   2021-01-03
```

* Add query param: `?registrationDate=2020-07-01` (registrationDate should be the nearest matching `registrated_at` date in the present or past, not future). Something like `filter(registered_at__lte=2020-07-01).order_by(registered_at).first()`

If you look closely to the timelines above:

* `?registrationDate=2021-01-02` will return record 1
* `?date=2021-01-02` will return record 2

**Comment by joeribekker** [comment]
Added to single object and list object retrieval.

* `registrationDate=2020-11-10` (filters on registration_date=...)
* `date=2020-11-10` (date should be between start_date and end_date)
