### ISSUE TITLE
Can we double check if these are required properties for a schema

### ISSUE THREAD

**Issue by joeribekker** [maykinmedia/objects-api#145]
For the schema in Objecttypes, shouldn't schema and ID of a JSON schema be mandatory?
Is the schema-prop auto added when creating an Objecttype with a schema without the schema-prop?

If something is auto-added, we need to document this.

*Observations by Ritense*

**Comment by annashamray** [comment]
According to JSON schema docs, none of the attributes is mandatory, even `{}` is a valid JSON schema 
Including `$id` and `$schema` to the schema is a best practice but not required

Documentation: https://json-schema.org/understanding-json-schema/basics.html

**Comment by joeribekker** [comment]
Alright. Thanks!
