### ISSUE TITLE
Test and rework history logic (part 1)

### ISSUE THREAD

**Issue by joeribekker** [maykinmedia/objects-api#168]
**Hints**

Documentation: https://www.gemmaonline.nl/images/gemmaonline/f/fa/Stuf0301.pdf

* Material history - `startAt` and `endAt` dates
* Formal history - `registeredAt` date.

Add the following JSON schema to mimic the StUF documentation on history (`PersoonId` is left out since its unused):

* `geslachtsnaam` (last name)
* `voorvoegsel` (prefix)
* `voorletters` (initials)
* `geboortedatum` (birthdate)
* `burgerlijkeStaat` (marital status)

The other attributes should be covered by our internal model:

* `volgnummer` - `index`
* `beginGeldigheid` - `startAt`
* `eindGeldigheid` - `endAt`
* `tijdstipRegistratie` - `registered_at`
* `volgnrNaCorrectie` - sort of covered by `correctionFor`

![image](https://user-images.githubusercontent.com/96970/111481330-2217d080-8733-11eb-8476-9beed72f62e6.png)

* [x] Test 1: If only record 1 (record with `volgnummer`=1) exists, **material history and formal history** on 01-01-2020 should say: _Record 1_
* [x] Test 1b: If only record 1 exists, **material history and formal history** on **01-01-1975** should say: _No record_.
* [x] Test 2a: If records 1 and 40 exists, **material history and formal history** on **01-01-2020** should say: _Record 40_
* [x] Test 2b: If records 1 and 40 exists, **material history and formal history** on **01-01-1975** should say: _No record_.
* [x] Test 3a: If records 1, 40 and 50 exists, **material history and formal history** on **01-01-2020** should say: _Record 50_
* [x] Test 3b: If records 1, 40 and 50 exists, **material history and formal history** on **01-01-1975** should say: _No record_.

![image](https://user-images.githubusercontent.com/96970/111490349-3d86d980-873b-11eb-9fee-7e7c91753c77.png)

Note: The history is changed here, not by API calls but just a new usecase. His name was registered incorrectly on 20010910 and record 40 corrected record 10. Ordering on `registratedAt` shows this.

* [x] Test 4a: **material history and formal history** on **01-01-2020** should say: Record 50
* [ ] Test 4b: **material history** on **01-10-2001** should say: Records 10 and 40 (both are material records on that date).
* [x] Test 4c: **formal history** on **01-10-2001** should say: Record 40 (since it was registered later than record 10)
* [x] Test 4d: **material history and formal history** on **01-01-1975** should say: _No record_.

![image](https://user-images.githubusercontent.com/96970/111491286-05cc6180-873c-11eb-8dba-73b86b6bd0a7.png)

Note: New scenario: Record 10 had an incorrect `startAt` date! So, 40 was still added to correct 10 but we cannot order on `startAt` alone anymore to decide the correct record. Corrections should be taken into account.

* [x] Test 5a: **material history and formal history** on **01-01-2020** should say: Record 50
* [ ] Test 5b: **material history** on **01-10-2001** should say: Records 10 and 40 (both are material records on that date).
* [x] Test 5c: **material history** on **04-09-2001** should say: Record 10.
* [x] Test 5d: **formal history** on **01-10-2001** should say: Record 40 (since it was registered later than record 10)
* [x] Test 5e: **formal history** on **04-09-2001** should say: Record 40 (since record 10 was corrected by record 40)
* [x] Test 5f: **material history and formal history** on **01-01-1975** should say: _No record_.
* [ ] Test 5g: **formal history** for the entire object, should show records 1, 40, 50
* [x] Test 5h: **material history** for the entire object, should show all records (always)

**Comment by annashamray** [comment]
@joeribekker 

> Test 4b: material history on 01-10-2001 should say: Records 10 and 40 (both are material records on that date).
> Test 5b: material history on 01-10-2001 should say: Records 10 and 40 (both are material records on that date).

Now we show the last record which fits the date. If two records have to be shown we need to change `Object.record` atribute from `object` to `array` in the OAS and implementation.

**Comment by annashamray** [comment]
@joeribekker 
> Test 4c: formal history on 01-10-2001 should say: Record 40 (since it was registered later than record 10)

Formal history on 01-10-2001 should say: Record 10, because Record 40 was registered 02-11-2001, i.e. later than 01-10-2001

**Comment by annashamray** [comment]
@joeribekker 
> Test 5c: material history on 04-09-2001 should say: Record 10.

Record 10 starts at 05-09-2001, and Record 40 starts at 03-09-2001. Therefore material history on 04-09-2001 should say: Record 40.

**Comment by annashamray** [comment]
@joeribekker 
> Test 5g: formal history for the entire object, should show records 1, 40, 50
Test 5h: material history for the entire object, should show all records (always)

For now we have only `history` endpoint that shows all the records for the particular object. We don't have an endpoint to show different types of history.

**Comment by joeribekker** [comment]
All your comments are valid!
