### ISSUE TITLE
Cleanup the performance fixture to the bare minimum

### ISSUE THREAD

**Issue by joeribekker** [maykinmedia/objects-api#217]
Things lke sesssion, users, admin_index, axes logs, etc. should all be removed. I think we should just keep:

- token
- object
- objectrecord
- objecttype
- global config (to reach the objecttypes api)

**Comment by dariomory** [comment]
Fixed in https://github.com/maykinmedia/objects-api-performance/commit/7436335fdc362426641e1aa715236d452a1e1ea5
