### ISSUE TITLE
As a developer, I need the possibility to do a non exact partial search on any of the properties.

### ISSUE THREAD

**Issue by svenvandescheur** [maykinmedia/objects-api#235]
This is beneficial for search.

**Update after refinement:**

So there would be support for two options:

* [x] `data_attr` query param will have a new operator `icontains` which filters with `ilike` string values - PR #239
* [x] new query param `data_icontains` will be introduced which allows `ilike` for all string values of  the JSON `data` - PR #242

**OLD:**
~~Clearification~~

~~* Add `_cached_data_values` to object model, to store all values from the `data` field~~
~~* Add `data_contains` to the API search endpoint, to search through `_cached_data_values` field~~

**Comment by annashamray** [comment]
@svenvandescheur Does `icontains` cover what you need in this issue?

**Comment by svenvandescheur** [comment]
@annashamray icontains can fix the issue where results are not matched because of capitalization. However, this does not fix the issue where a property is not defined from the frontend.

Properties are not known by the user and IMO we should not expect the user to know. I also would like to keep the search simple and not clutter the interface with all kind of property selection. In short: I expect to be able to query "vleuten" an the API will show results where the property "adres" is "Vleutenseweg 169" as well as the result for the "Vleutensebrug" (property name). 

I think allowing icontains improves the usability of the __filter__ but this does not resolve the need for a __search__.

**Comment by annashamray** [comment]
@svenvandescheur I don't quite get it why `icontains` won't help in the example that you provided. 
Afaik django-admin search uses `icontains` under the hood.

**Comment by svenvandescheur** [comment]
@annashamray zaak objecten have various properties, the syntax AFAIK will be <property_key>__icontains__<property_value>. Which requires knowledge of the property key, something which is not present.

Instead I would like to do something like ?search=<property_value>.

**Comment by annashamray** [comment]
But you can know property keys from the objecttype of the object. 

I don't actually know that the desired behaviour of the search on data without property names can be implemented keeping in mind all the nesting. 
I'll assign this to @joeribekker to discuss what should we do with this user story

**Comment by joeribekker** [comment]
I think it means to consider the data (dict) as a big blob and just search through it as if it were a big string.

This is getting close to an elastic search endpoint that I joked about earlier :)

**Comment by annashamray** [comment]
A quick search says that Postgres JSON field doesn't support this kind of search, so it should be done on python level, which can take a tremendous amount of time. So yeah, I don't think it's possible with the current realization

On the other hand we provide the client with the info about all possible properties in the related object type. So the client actually knows the names of attributes and their structure

**Comment by annashamray** [comment]
After researching a little more I found that Postgres 12 started supporting json path. 
This will allow us to do recursive regex search on `jsonb` field optimized by DB. 

The downside is that Postgres 10 (which is our current requirement for the Objects API) doesn't support it. 
I believe this is the most optimal way how to do this search, so I suggest one of two options:

* support the search with `data_contains` only if Postgres version >= 12. 
* make conditional implementation: if Postgres 12+ then do the search with json path, if not then convert `jsonb` field to the `text` on fly and use `like` for the text blob

Both of the options could be done without  creating `_cached_data_values` and not increasing DB size

**Comment by joeribekker** [comment]
I like pg12 but let's then only add it to V2 of the api

**Comment by annashamray** [comment]
After some refinement with Utrecht it was decided that they need filtering on data properties with known property names, so `icontains` to `data_attrs` will be also added

**Comment by annashamray** [comment]
implemented in #239 and #242
