### ISSUE TITLE
Demo objecttypes data doesn't match demo object data

### ISSUE THREAD

**Issue by joeribekker** [maykinmedia/objects-api#269]
Are trees present in objecttypes? We do have trees in objects.

**Comment by ErhanCitil** [comment]
![afbeelding](https://github.com/maykinmedia/objects-api/assets/90844114/e864da49-5c26-4166-bdf0-f33a47b86767)
Yes trees are present in objecttypes @joeribekker

**Comment by joeribekker** [comment]
So, does our demo fixture match up?

**Comment by ErhanCitil** [comment]
Yes it does
