### ISSUE TITLE
Permissions admin page crashed when json schema doesn't have properties

### ISSUE THREAD

**Issue by annashamray** [maykinmedia/objects-api#273]
The permission change page in the Objects Admin crashes when any of jsonschemas in any of objecttype.version doesn't have `properties` attribute
Json schemas without `properties` are still valid ones, so the case with absent properties should be process correctly

**Comment by JurjenBert** [comment]
Hi @annashamray! we deployed 2.0.0 but it seems we still run into this issue. Do you know if this should be fixed in 2.0.0?

**Comment by annashamray** [comment]
@JurjenBert yes, sorry. 2.0.0 version was released before this bug was fixed.
You can use `latest` version or wait for 2.1.0 release which is WIP (you can track it here https://github.com/maykinmedia/objects-api/pull/278)
