### ISSUE TITLE
Filter `typeVersion` field on the `/objects` endpoint

### ISSUE THREAD

**Issue by Viicos** [maykinmedia/objects-api#306]
Although it doesn't really make sense to filter objects according to their type version, as objects with different objecttypes can have the same version number, it is useful on my end when filtering objects with the `type` url field to have the ability to filter the versions as well.

This shouldn't be too hard to implement, so if you are ok with this feature I can make a PR. (I understand this is something you would not want to have for the reason stated above).

**Comment by joeribekker** [comment]
I don't have a problem with it. You @annashamray ?

You can make a PR @Viicos if you want! Much appreciated.

**Comment by annashamray** [comment]
It's a good idea! I'll assign this issue on @Viicos
