### ISSUE TITLE
400 bad request bij draaien docker image

### ISSUE THREAD

**Issue by frankmijn** [maykinmedia/objects-api#313]
Aan de hand van de instructies op readthedocs wilde ik een lokale versie van de objects-api en de objecttypes-api draaien. Ik heb hierbij gekozen voor de optie om Docker-containers binnen te halen. Waar ik alleen tegenaan loop, is dat ik op elk request een 400 (bad request) terugkrijg. Ik zie ook niets verschijnen in de logging in de container. Speelt zwel bij objects-api als objecttypes-api.

Hoewel ik hier weinig kennis van heb, heb ik een beetje gegraven en het viel me op dat ik in /src/objects/conf/docker.py niets zie staan dat de ALLOWED_HOSTS definieert. Maar het kan ook bewust zijn dat deze hier ontbreekt en er nog een environment-bestand aangemaakt moet worden dat ik niet in de docs ben tegengekomen. En er is een nog grotere kans dat het iets volledig anders is.

Welke dingen kan ik delen om tot diagnostiek te komen?

**Comment by joeribekker** [comment]
Samen met je documentatie ticket, zal ik er zelf weer even doorheen lopen en checken wat er aan de hand is.

**Comment by stevenbal** [comment]
probleem is inmiddels gefixed
