### ISSUE TITLE
installatieinstructies op quickstart

### ISSUE THREAD

**Issue by frankmijn** [maykinmedia/objects-api#314]
Op https://objects-and-objecttypes-api.readthedocs.io/en/latest/installation/quickstart.html staan instructies voor het draaien van de docker images. Hier ben ik (op mijn installatie) tegen de volgende (eenvoudig oplosbare) zaken aangelopen:

- Deze instructies gaan uit van docker-compose. Als je de laatste versie van docker installeert, kreeg je deze niet meer mee. Dan moet het docker compose zijn. 
- De containers kregen bij mij een andere naam dan 'web'
- Ik kreeg bij het uitvoeren van de docker exec instructies een foutmelding kreeg over geen TTY. Dit was op te lossen door het toevoegen van -it bij de aanroep. 

Overigens wel complimenten voor de documentatie, het was gewoon goed en makkelijk te volgen.

**Comment by joeribekker** [comment]
Bedankt voor de tips! Erg fijn dat je deze terug communiceert!

**Comment by annashamray** [comment]
Duplicate https://github.com/maykinmedia/objects-api/issues/348
