### ISSUE TITLE
As developer, I want objects written to the data-attribute to not include more properties as specified in the schema

### ISSUE THREAD

**Issue by joeribekker** [maykinmedia/objects-api#32]

**Comment by annashamray** [comment]
According to JSON schema docs this kind of behavior should be specified inside the JSON schema (https://json-schema.org/understanding-json-schema/reference/object.html#id2)

If `"additionalProperties": false` in the schema, then the JSON with extra properties would be invalid. The default value for  `additionalProperties` = True

**Comment by joeribekker** [comment]
Fair enough.
