### ISSUE TITLE
Objects API admin: Show Object data as JSON

### ISSUE THREAD

**Issue by alextreme** [maykinmedia/objects-api#322]
When viewing the Object data in the admin, it is quite annoying that the data is shown as a Python dict instead of (what you would expect) a JSON blob:

![image](https://user-images.githubusercontent.com/226839/223702804-a87c7a58-62ce-444d-af2c-973d7c5fe356.png)

I would recommend to show the Objects as JSON, this to ease copy-pasting data and making this consistent with the ObjectTypes (which are shown as JSON)

**Comment by alextreme** [comment]
Also mentioned by Den Haag.

@ErhanCitil would you mind giving this issue a try?

**Comment by bart-maykin** [comment]
The data field already gets served as json.
