### ISSUE TITLE
As a developer I would like to get a specific version of an object

### ISSUE THREAD

**Issue by ferdi-ritense** [maykinmedia/objects-api#328]
At this moment it is only possible to return the complete history of an object using `/api/v2/objects/{uuid}/history`. For objects with a large number of versions this is quite a heavy call. Often we already know the specific version we want and don't need all the other ones.

It would be really helpful to be able to request a specific version of an object, for example using `/api/v2/objects/{uuid}/history/{version}`

**Comment by sdegroot** [comment]
Probably it should be `GET /api/v2/objects/{uuid}/{version}`

**Comment by joeribekker** [comment]
Planned to be released in end of August.
