### ISSUE TITLE
Hijack functie in de admin voor User lijkt niet (goed) te werken

### ISSUE THREAD

**Issue by alextreme** [maykinmedia/objects-api#336]
Gemeld door @LaurensBurger , Utrecht Taiga nr 64

Hijack lijkt het volgens Utrecht niet meer te doen. Graag controleren of dit inderdaad klopt en zo ja herstellen. Laurens vermoed dat het ligt aan django-two-factor-auth, maar het zou ook een kwestie kunnen zijn van de hijack-library updaten.

Na uitzoeken en corrigeren dit tevens verhelpen voor de objecttypes, daar zou hetzelfde probleem spelen.

**Comment by ErhanCitil** [comment]
@alextreme  Ik heb het eventjes uitgetest en bij mij werkt het wel naar behoren. Ik heb geprobeerd zonder de twee factor authenticatie en MET de twee factor authenticatie. Als ik gewoon op hijack druk dan word ik automatisch ingelogd zonder dat er een code of iets anders er voor gevraagd wordt.

**Comment by alextreme** [comment]
Zou je dit morgen met @LaurensBurger  kunnen bespreken? Wellicht ligt het aan het ingelogd zijn met OIDC, en is dit bewust voor die beheerders uitgeschakeld.
