### ISSUE TITLE
Add log-outgoing-requests to Objects API

### ISSUE THREAD

**Issue by alextreme** [maykinmedia/objects-api#344]
During debugging an Objects API - Open Notificaties issue Laurens and I noticed we don't have https://github.com/maykinmedia/django-log-outgoing-requests installed in the project. Please do so, it should give proper insight into what the Objects API is doing (both to OT API and ON)

**Comment by ErhanCitil** [comment]
Het is beter als ik deze toevoeg na het updaten van de project naar Django versie 3.2, omdat de package werkt op DJango 4.2. @alextreme

**Comment by alextreme** [comment]
@ErhanCitil dat is prima, django-log-outgoing-requests heeft inderdaad minimaal 3.2 nodig.
