### ISSUE TITLE
Controle dat Objecten API werkt zonder Open Notificaties 

### ISSUE THREAD

**Issue by alextreme** [maykinmedia/objects-api#346]
Ondervonden met Objecten API dat we via de objects_create API endpoint geen objecten kunnen aanmaken zonder Open Notificaties te hebben ingericht.

Graag je controle hierop

**Comment by ErhanCitil** [comment]
Ik loop hier tegen aan met mijn tests bij deze [pull request](https://github.com/maykinmedia/objects-api/actions/runs/5750533259/job/15587498267?pr=341). Je moet inderdaad Open Notificaties inrichten om een object te kunnen aanmaken. @alextreme

**Comment by alextreme** [comment]
@ErhanCitil duidelijk even met Sjoerd en Joeri aan het kijken en dit zou volgens mij wel goed moeten gaan met de vervanging van vng-api-common (namelijk notifications-api-common) of wanneer je NOTIFICATIONS_DISABLED envvar instelt . Voor nu is ON inderdaad verplicht by default

**Comment by ErhanCitil** [comment]
> n) of wanneer je NOTIFICATIONS

In die pull request update ik Django naar versie 3.2 en daarbij gebruik ik notifications-api-common, dus daarom test ik het daar met notifications-api-common maar het is alsnog nodig om een nieuwe object te kunnen aanamaken. Dus ik denk  dat ik NOTIFICATIONS_DISABLED envvar moet instellen.
