### ISSUE TITLE
Question: How to find objects on the value of properties within an array

### ISSUE THREAD

**Issue by sytskevanhasselt** [maykinmedia/objects-api#347]
We have an object type, interneTaak, that includes an array of sub-objects. So each object can contain more than one `digitaalAdres`. A property of `digitaalAdres `is `adres`, which may contain a phone number, or e-mail address. We would like to search for these objects, on the value of the property `adres`. 

The specification describes several ways to retrieve a list of objects, based on search parameters (GET object_list, POST object_search). Both methods provide two ways of filtering on the value of properties within the object:

- **data_icontains**: Search in all data values of string properties. 
This is a type of full text search.	
- **data_attrs**: Only include objects that have attributes with certain values.

The latter one offers data filtering expressions, using operators like exact, gt, lt etc. The specification describes how to search for attributes that are nested: 

> Example: in order to display only objects with `height` equal to 100, query `data_attrs=height__exact__100` should be used. If `height` is nested inside `dimensions` attribute, query should look like `data_attrs=dimensions__height__exact__100`

But this doesn’t seem to work on attributes within an array. I can only find these objects using data_icontains. But in this case, that is not precise enough. 

Say we have an object that has the following digitalAdressen, where digitaleAdressen is nested in betrokkene:

```
{​​​​​​​
    "betrokkene": {​​​​​​​​​​​​​​
               "persoonsnaam": {​​​​​​​​​​​​​​
                      "voornaam": "Piet",
                      "achternaam": "Puck",
                     "voorvoegselAchternaam": "van"
                         }​​​​​​​​​​​​​​,
        "digitaleAdressen": [
            {​​​​​​​​​​​​​​
                "adres": donald@duckstad.nl,
                "omschrijving": "e-mailadres",
                "soortDigitaalAdres": "e-mailadres"
            }​​​​​​​​​​​​​​,
            {​​​​​​​​​​​​​​
                "adres": "0123456789",
                "omschrijving": "telefoonnummer",
                "soortDigitaalAdres": "telefoonnummer"
            }​​​​​​​​​​​​​​
        ]
    }​​​​​​​​​​​​​​
}​​​​​​​​​​​​​​
```

I cán find this object with a search, using: 

`"data_attrs": "betrokkene__persoonsnaam__achternaam__exact__Puck"`

But I cannot find this object with a search using 

` "data_attrs": "betrokkene__digitaleAdressen__adres__exact__0123456789"`

This is no doubt because it is an array. 

So how would I go about finding objects, that have a property `adres`, with the value `0123456789`, whether it’s in the first `digitaalAdres`, the second, the third, etc? Or is this not possible at this moment?

**Comment by annashamray** [comment]
There are two ways how you can filter on attributes within the arrays in the `data` now:
1. `data_icontains` as you mentioned yourself, so in this case it would be `"data_icontains": "0123456789"` 
2. If you know which member of the array you are looking for, you can use following syntax:
` "data_attrs": "betrokkene__digitaleAdressen__<index of the array member - 1>__adres__exact__<value>"` 
So in this example:
* `"data_attrs": "betrokkene__digitaleAdressen__0__adres__exact__0123456789"` will check the first member of the `digitaleAdressen` array and will return empty list
* `"data_attrs": "betrokkene__digitaleAdressen__1__adres__exact__0123456789"` will check the second member of the `digitaleAdressen` array and will return the list with this object. 

With `data_attrs` query param you check the particular member of the array and you need to specify its index. 
If you don't know the index or it doesn't matter then you can use `data_icontains`

**Comment by sytskevanhasselt** [comment]
Thank you for your reply. Since we don't know in which member of the array a number would appear, I understand we have to use `icontains`. It will return slightly more than we need. But I find we can narrow the result down further by using a combination of `data_attrs`, and `icontains` as operator on the `digitaleAdressen`-attribute. 
So: `"data_attrs": "betrokkene__digitaleAdressen__icontains__0123456789"`.

**Comment by sytskevanhasselt** [comment]
Since my question has been answered (a long time ago, my apologies), i will close my issue.
