### ISSUE TITLE
Adding strictly confidential as data classification doesn't fit in the field length

### ISSUE THREAD

**Issue by joeribekker** [maykinmedia/objects-api#350]
Ref: Taiga DH 525

![image](https://github.com/maykinmedia/objects-api/assets/96970/afac53f2-89a3-4dbd-a54f-f2889a3bf683)

**Comment by annashamray** [comment]
@joeribekker @alextreme It works for me in the latest Objecttypes version (2.1.2)
Could you reproduce this error?

**Comment by alextreme** [comment]
Yes you fixed this last year:
https://github.com/maykinmedia/objecttypes-api/blob/master/src/objecttypes/core/migrations/0018_auto_20230207_1401.py
