### ISSUE TITLE
Partial update (PATCH) of an object replaces data

### ISSUE THREAD

**Issue by SilviaAmAm** [maykinmedia/objects-api#351]
After creating an object with multiple properties in the "data" field, doing a PATCH call to update one of the properties in data overwrites the whole data field.

# Steps to reproduce

(with a fake URL for the environment, but tested on our test environment)

1. Create an object: POST https://objecten.test.nl/api/v2/objects

```json
{
    "type": "https://objecttypen.test.nl/api/v2/objecttypes/2360a778-6747-47b4-ad2b-e5e281336bba",
    "record": {
        "typeVersion": 2,
        "data": {
            "type": "Fruitteelt",
            "leeftijd": 100,
            "kiemjaar": 2002
        },
        "geometry": {
            "type": "Point",
            "coordinates": [
                4.766006469726562,
                52.29066294826172
            ]
        },
        "startAt": "2023-12-01"
    }
}
```
2. Update the object (PATCH https://objecten.test.nl/api/v2/objects/19fadf7f-5695-41a1-9de8-a7246b1c28a3)

```json
{
    "record": {
        "data": {
            "kiemjaar": 2012
        },
        "startAt": "2023-12-01"
    }
}
```

This then returns the following object:
```json
{
    "url": "https://objecten.test.nl/api/v2/objects/19fadf7f-5695-41a1-9de8-a7246b1c28a3",
    "uuid": "19fadf7f-5695-41a1-9de8-a7246b1c28a3",
    "type": "https://objecttypen.test.nl/api/v2/objecttypes/2360a778-6747-47b4-ad2b-e5e281336bba",
    "record": {
        "index": 2,
        "typeVersion": 2,
        "data": {
            "kiemjaar": 2012
        },
        "geometry": null,
        "startAt": "2023-12-01",
        "endAt": null,
        "registrationAt": "2023-12-01",
        "correctionFor": null,
        "correctedBy": null
    }
}
```
The `data` field is missing the `type` and the `leeftijd` attributes that were set when first creating the object.

**Comment by joeribekker** [comment]
Refinement: 

Discussion involves: 

Add support for `Content-Type: application/merge-patch+json` to merge the "data"

* https://kubernetes.io/docs/tasks/manage-kubernetes-objects/update-api-object-kubectl-patch/
* https://datatracker.ietf.org/doc/html/rfc7386
