### ISSUE TITLE
Update to mozilla-django-oidc-db 0.13.0

### ISSUE THREAD

**Issue by joeribekker** [maykinmedia/objects-api#354]
To add superuser support

Please also add it for objecttypes API.

**Comment by Coperh** [comment]
Already upgraded to 0.14.1 in Objects-api;
https://github.com/maykinmedia/objects-api/blob/5f60a5bc919d7984f6a72628764b56c67dbcc26e/requirements/base.txt#L207

**Comment by Coperh** [comment]
Also added to objecttypes-api:
https://github.com/maykinmedia/objecttypes-api/blob/ff3e275cdd6740c277bc116f3c1727e9e93ee49b/requirements/base.txt#L205

**Comment by Coperh** [comment]
Also can confirm it is updated in requirements `ci.txt` and `dev.txt` in both project
