### ISSUE TITLE
Run docker-compose in Github Actions

### ISSUE THREAD

**Issue by alextreme** [maykinmedia/objects-api#384]
Due to https://github.com/maykinmedia/objects-api/pull/376 I would recommend adding a docker-compose run to Github actions, this to ensure celery is running as expected

**Comment by annashamray** [comment]
@alextreme Does this PR work for you for this issue? https://github.com/maykinmedia/objects-api/pull/409

**Comment by alextreme** [comment]
@annashamray Sure that works for me

**Comment by annashamray** [comment]
#409 is merged into the master branch
