### ISSUE TITLE
Login page style with OIDC enabled is off

### ISSUE THREAD

**Issue by annashamray** [maykinmedia/objects-api#392]
### Product versie / Product version

Objects API and Objecttypes API

### Omschrijf het probleem / Describe the bug

In the login page to the admin a link to log with OIDC is not centered:
![image (5)](https://github.com/maykinmedia/objects-api/assets/47745906/c8eb1900-272f-4557-9603-c91bc5d055f7)

**Comment by stevenbal** [comment]
Not sure if this is also a problem for Open Klant, but it would be good to check

**Comment by Coperh** [comment]
Open Klant displays correclty
