### ISSUE TITLE
Document notification configuration usage

### ISSUE THREAD

**Issue by alextreme** [maykinmedia/objects-api#403]
### Thema / Theme

Admin

### Omschrijving / Description

Dimpact 83

Currently the retry-mechanism is in the Objects API, however it isn't easy to figure out how to use it. These options in the admin aren't documented (not in the objects API documentaiton and also not in https://notifications-api-common.readthedocs.io ). 

It would also be preferable to re-generate notifications for an objects somehow

![image](https://github.com/maykinmedia/objects-api/assets/226839/0dafd302-4da1-4088-b033-6b2c887cdc4a)

**Comment by joeribekker** [comment]
Estimate: 1 day

**Comment by joeribekker** [comment]
@annashamray indicated theres already a page for notifications, so we can just update it. @stevenbal mentions Open Zaak has this documented. The page: https://objects-and-objecttypes-api.readthedocs.io/en/latest/admin/notifications.html#notifications

**Comment by joeribekker** [comment]
W're leaving out the option to regenerate notifications
