### ISSUE TITLE
Token auth doesn't load in propperly in admin/token/permission/{id}/change/

### ISSUE THREAD

**Issue by bart-maykin** [maykinmedia/objects-api#404]
![Screenshot from 2024-05-14 09-25-08](https://github.com/maykinmedia/objects-api/assets/101265650/89a977fe-babe-474e-a880-2d942a0ccaa9)

When opening the permission detail page the token auth field doesn't select the correct object but instead displays that nothing is selected.

**Comment by joeribekker** [comment]
duplicate of #406
