### ISSUE TITLE
Objects API - Permissions edit-view doesn't show the Token auth for the permission

### ISSUE THREAD

**Issue by alextreme** [maykinmedia/objects-api#406]
### Product versie / Product version

2.3.1

### Omschrijf het probleem / Describe the bug

Taiga Dimpact 81

When viewing an Objects API Permission in the admin (API Authorization → Permissions), the Token Auth foreign key field appears to be unselected, even though the Permission always has a Token Auth (mandatory FK).

When viewing the Token Authentication in the admin (API Authorization → Token authentication) with the related Permissions the relationship is shown as expected, as such this issue is merely a problem when using the Permission admin interface as an alternative.

The Taiga issue has a gif demonstrating the behaviour to clarify

**Comment by joeribekker** [comment]
Estimate: 3 days (because its react)

**Comment by joeribekker** [comment]
Refinement: Closing because cannot be reproduced.
