### ISSUE TITLE
Search in objects `data_attrs` using "OR"

### ISSUE THREAD

**Issue by joeribekker** [maykinmedia/objects-api#411]
### Thema / Theme

Objecten API

### Omschrijving / Description

Example query: Return all task(objects) that belong to one of the provided casenumbers

**Comment by joeribekker** [comment]
Estimated: This needs investigation, but probably takes a few weeks. We also need to to know what exactly is needed here because combining AND and OR and the ordering of elements will make this harder.

For example, we need to introduce braces and a different format to support OR, like:

```data_attrs=(dimensions__height__exact__100,width__exact__200)|color=blue```

**Comment by joeribekker** [comment]
@JanBrek Waiting for clarrification and approval.

**Comment by joeribekker** [comment]
@JanBrek ping

**Comment by JanBrek** [comment]
@joeribekker I think we can close this as our usecase is covered with __in operator (Separate ticket)
