### ISSUE TITLE
Tokens can be exposed via the URL when viewing their detailpage via the admin

### ISSUE THREAD

**Issue by alextreme** [maykinmedia/objects-api#445]
### Thema / Theme

Admin

### Omschrijving / Description

DH Taiga 589

When browsing the admin and viewing the detailpage of a tokenauth /admin/token/tokenauth/ the authentication token is shown in the URL as it is also used as the primary key. This has risks due to webserverlogs/gatewaylogs.

I'd recommend to always use the default 'id' as primary key, or a separate uuid-field unrelated to credentials because of this risk

**Comment by alextreme** [comment]
Discussed, estimated at 1 day max to implement the suggested change

@PeterVanBragt: ready for approval.

**Comment by PeterVanBragt** [comment]
Approved

**Comment by bart-maykin** [comment]
![image](https://github.com/user-attachments/assets/48d91955-9578-4389-b4d8-2c12fae60939)

It seems like this issue is already resolved @alextreme.
