### ISSUE TITLE
Management command to auto-generate objects for objecttypes

### ISSUE THREAD

**Issue by alextreme** [maykinmedia/objects-api#451]
### Thema / Theme

Objecten API

### Omschrijving / Description

Taiga DH 565

> 
> Voor performance tests in den haag van de objecten API.
> 
> - Aantal aangewezen objectTypes
> - Waarbij randomized objecten/versies van gemaakt worden op basis van het type (Dus random enum selectie, random number, etc)
> - Out of scope: niet bestaande optionele velden

----

To be investigated what the options are to auto-generate JSON from a JSON schema. There are online tools for this, a quick search shows a few Python options on SO: https://stackoverflow.com/questions/35231234/python-json-dummy-data-generation-from-json-schema

**Comment by JanBrek** [comment]
@alextreme Onze nieuwe collega Kevin gaat hier al mee aan de slag.
Dus dit ticket hoeft niet meer gedaan te worden.
