### ISSUE TITLE
Remove Objects API v1

### ISSUE THREAD

**Issue by alextreme** [maykinmedia/objects-api#453]
### Thema / Theme

Objecten API

### Omschrijving / Description

The Objects API v1 has been deprecated for a few years now, lets remove it asap

**Tasks**
* [x] Objects API https://github.com/maykinmedia/objects-api/pull/456
* [x] Objecttypes API https://github.com/maykinmedia/objecttypes-api/pull/130

### Toegevoegde waarde / Added value

Less code, less maintenance, less confusion with users

**Comment by joeribekker** [comment]
Refinement: This will trigger a 3.0 release for the Objects API.

**Comment by shazada** [comment]
Hi @annashamray we're now in te proces to implement v2.
But if you've created v1 Objects (which we've done), is there a migration path/script etc. how to migratie to v2?

What we've seen, is that v1 created Objects don't return results on v2.
Thanks
