### ISSUE TITLE
As productowner, I want to see a checklist in the docs of all API-guidelines that we passed

### ISSUE THREAD

**Issue by joeribekker** [maykinmedia/objects-api#47]
Documented here: https://docs.geostandaarden.nl/api/API-Strategie/
meaning this list here: https://docs.geostandaarden.nl/api/API-Designrules/

**Comment by annashamray** [comment]
Also, API Test Platform can test (https://api-test.nl/) against API design rules. We can test our APIs and then include the links to the results in the documentation

**Comment by joeribekker** [comment]
Sounds good

Vriendelijke groet / Best regards,

Joeri Bekker
(verzonden vanaf mobiel)

--
Maykin Media
Keizersgracht 117, 1015 CJ Amsterdam
tel.: +31 (0)20 753 05 23
http://www.maykinmedia.nl

Op wo 11 nov. 2020 12:16 schreef annashamray <notifications@github.com>:

**Comment by annashamray** [comment]
Links are added to the PR
