### ISSUE TITLE
As a staff member, I want to be able to use my ADFS login

### ISSUE THREAD

**Issue by sergei-maertens** [maykinmedia/objects-api#96]
Many organizations make use of ADFS for single sign on. The package https://pypi.org/project/django-auth-adfs-db/ should be integrated to add plug-and-play ADFS sign-in to the projects.

**Comment by JurjenBert** [comment]
@sergei-maertens isn't this resolved with the login with org account? (available in both objects and objecttypes admin)
![afbeelding](https://user-images.githubusercontent.com/40294293/220301644-617faf94-934e-4665-86da-11b83d20d4e3.png)
